name: CSS Lint
on:
  pull_request:
    types: [labeled]

jobs:
  label_job:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'aemy-css-lint'
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm run lint:css -- --fix
