name: CSS Lint
on:
  pull_request:
    types: [labeled]

jobs:
  label_job:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'aemy-lint-css'
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      issues: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm install
    - run: npm run lint:css -- --fix
    - name: Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Auto-commit: Apply css lint fixes"
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: aemy-css-lint
